accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

coin4u/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('polls/', include('polls.urls', namespace="polls")),
    path('calendar/', include('calendarapp.urls')),
    path('news/', include('newsapp.urls')),
    path('', include('indicatorapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('', views.polls_list, name='index'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.end_poll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/', views.choice_delete, name='choice_delete'),
    path('<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),

]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy    # reverse는 함수형 view에서, reverse_lazy는 class형 view에서 사용.
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld

has_ownership_list = [
    login_required,
    account_ownership_required,
]

def hello_world(request):
    if request.method == "POST":
        temp = request.POST.get('hello_world_input')
        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list' : hello_world_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


@method_decorator(has_ownership_list, 'get')
@method_decorator(has_ownership_list, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'


@method_decorator(has_ownership_list, 'get')
@method_decorator(has_ownership_list, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>SignUp</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div>
        {% if target_user.profile %}
        <img src="{{ target_user.profile.image.url }}" alt="" style="height: 8rem; width 8rem; border-radius: 10rem; margin-bottom: 2rem;">
        <h1>
            {{ target_user.profile.nickname }}
        </h1>
        <h5 style="margin-bottom: 2rem; font-size: 18px;">
            {{ target_user.profile.message }}
        </h5>

        <p>
            {% if target_user == user %}
            <a class="btn btn-dark left" style="width: 100%; margin: 5px;" href="{% url 'profileapp:update' pk=target_user.profile.pk %}"> Edit your profile </a>
            {% endif %}
        </p>

        {% else %}
        {% if target_user == user %}
        <a class="btn btn-dark left" style="width: 100%; margin: 5px;" href="{% url 'profileapp:create' %}"> Create Profile </a>
        {% endif %}
        {% endif %}

        {% if target_user == user %}
        <a class="btn btn-dark left" style="width: 100%; margin: 5px;" href="{% url 'profileapp:update' pk=user.pk %}"> Change Info </a>
        <a class="btn btn-danger left" style="width: 100%; margin: 5px;" href="{% url 'accountapp:delete' pk=user.pk %}"> Delete </a>
        {% endif %}
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}}

{% block content %}

<div style="height: 30rem auto;">
    <form action="/accounts/hello_world/" method="post">
        {% csrf_token %}
        <div>
            <input type="text" name="hello_world_input">
        </div>
        <div>
            <input type="submit" class="btn btn-primary" value="POST">
        </div>
    </form>

    {% if hello_world_list %}
        {% for hello_world in hello_world_list %}
        <h2>
            {{ hello_world.text }}
        </h2>
        {% endfor %}
    {% endif %}
</div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div>
        <h4>Login</h4>
    </div>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>SignUp</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}