accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

calendarapp/urls.py
from django.urls import path

from .views import CalendarView, TestView, crawler

app_name = 'calendarapp'

urlpatterns = [
    path('', CalendarView.as_view(), name='calendar'),
    path('test', TestView, name='test'),
    path("crawler", crawler, name="crawler"),
]

coin4u/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('polls/', include('polls.urls', namespace="polls")),
    path('calendar/', include('calendarapp.urls')),
    path('news/', include('newsapp.urls')),
    path('', include('indicatorapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

indicatorapp/urls.py
from django.urls import path, include
from . import views

app_name = "indicatorapp"

urlpatterns = [
    path("", views.indexView, name="index"),
    path('detail/', views.detailView, name="detail"),
    path('error/', views.detailView, name="error"),
    path("crawler/", views.crawler, name="crawler"),
    # path('test', views.TestView, name='test'),
]

newsapp/urls.py
# urls.py
from django.urls import path
from . import views
from .views import crawler

app_name = "newsapp"

urlpatterns = [
    path('', views.NewsView.as_view(), name='index'),
    path("crawler", crawler, name="crawler"),
] 

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('', views.polls_list, name='index'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.end_poll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/', views.choice_delete, name='choice_delete'),
    path('<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body class="d-flex flex-column min-vh-100">

    <div>
        {% include 'header.html' %}
    </div>

    <div>

        {% block content %}
        {% endblock %}

    </div>

    <div class="py-3 mt-auto">
        {% include 'footer.html' %}
    </div>

</body>
</html>

templates/footer.html
<div class="footer">
    <hr>
    <span>Contact: requests.selenium@gmail.com</span>
    <h6>INDICATORS</h6>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>INDICATORS</title>
    <!--  BOOTSTRAP LINK  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <!--  GOOGLE FONTS LINK  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">

    <!--  EDFAULT CSS LINK  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/calendarapp.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/newsapp.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/indicatorapp.css' %}">

    <!--  Chart.js  -->
    <script type="text/javascript" src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="https://cdn.canvasjs.com/canvasjs.stock.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/luxon@1.26.0"></script>
	<script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.1/dist/chart.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@1.0.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js/dist/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>

    <!--  FOR CALENDAR  -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!--  FOR DASH  -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>


</head>

templates/header.html
<div class="header">
    <!--  TITLE  -->
    <div>
        <a class="header" href="{% url 'indicatorapp:index' %}">
        <h1>INDICATORS</h1>
    </a>
    </div>
    <!--  CONTENT  -->
    <div>
        <a class="header" href="{% url 'indicatorapp:detail' %}">
            <span>Indicators</span>
        </a>
        <a class="header" href="{% url 'calendarapp:calendar' %}">
            <span>Earnings Calendar</span>
        </a>
        <a class="header" href="{% url 'newsapp:index' %}">
            <span>News</span>
        </a>
        {% if not user.is_authenticated %}
        <!--  login html로 가는데, 로그인하고나면 next에 적은 path로 이동해라라는 뜻  -->
        <a class="header" href="{% url 'accountapp:login' %}?next={{ request.path }}">
            <span>Login</span>
        </a>
        <a class="header" href="{% url 'accountapp:create' %}">
            <span>SignUp</span>
        </a>
        {% else %}
        <a class="header" href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>MyPage</span>
        </a>
        <a class="header" href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>Logout</span>
        </a>
        {% endif %}
    </div>
</div>
<hr>